apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimo-ingress
  namespace: mimo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mimo.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mimo-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mimo-frontend
                port:
                  number: 3000
